// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bookapi.data;

namespace bookapi.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20190806014845_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("bookapi.models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author")
                        .IsRequired();

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = " stien beck",
                            Category = "none",
                            Title = "The Grapes of Wrath"
                        },
                        new
                        {
                            Id = 2,
                            Author = "stien beck",
                            Category = "blue",
                            Title = "Cannery Row"
                        },
                        new
                        {
                            Id = 3,
                            Author = "stephen king",
                            Category = "boo",
                            Title = "The Shining"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
